# Setup
title:            Shivani Shah
tagline:          'Shivani Shah'
description:      'Graduate Student at University of Florida'
url:              https://sp-shah.github.io
baseurl:          /
paginate:         5

# About and contact
author: 
  name:           'Shivani Shah'
  url:            https://twitter.com/shivnshah95

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
