# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shivani P. Shah
tagline:          'Graduate Student at University of Florida'
description:      'Graduate Student at University of Florida'
url:              https://sp-shah.github.io/
baseurl:          /

author:
  name:           'Shivani Shah'
  url:            https://twitter.com/shivnshah95

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sp-shah
